---
# "Include" for unit tests definition.

remove_package_lock: &remove_package_lock
  name: Remove package-lock.json if needed.
  command: |
    WORKFLOW_NAME=`python .circleci/get_workflow_name.py`
    echo "Workflow name: $WORKFLOW_NAME"
    if [ "$WORKFLOW_NAME" = "nightly" ]; then
      echo "Nightly build detected, removing package-lock.json"
      rm -f package-lock.json
    else
      echo "Not a nightly build, skipping this step."
    fi

unit_tests: &unit_tests
  steps:
    - checkout
    - run: *remove_package_lock
    - run: npm install
    - run: npm test
    - run:
        name: Submit coverage data to codecov.
        command: node_modules/.bin/codecov
        when: always

# Testing the samples requires running `npm link` and
# `npm link googleapis`, which attempts to make a global
# change.  This leads to a permissions error unless the
# global npm module directory is changed.  These samples
# only tested against latest LTS.
test_samples: &test_samples
  steps:
    - checkout
    - run: *remove_package_lock
    - run: npm install
    - run: mkdir ~/.npm-packages
    - run: echo "prefix = $HOME/.npm-packages" >> ~/.npmrc
    - run: export PATH=~/.npm-packages/bin:$PATH
    - run: make && make test-samples

version: 2.0
workflows:
  version: 2
  tests:
    jobs: &workflow_jobs
      - node6:
          filters:
            tags:
              only: /.*/
      - node8:
          filters:
            tags:
              only: /.*/
      - node10:
          filters:
            tags:
              only: /.*/
      - publish_npm:
          requires:
            - node6
            - node8
            - node10
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[\d.]+$/
      - publish_common:
          requires:
            - node6
            - node8
            - node10
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^googleapis-common@[\d.]+$/
  nightly:
    triggers:
      - schedule:
          cron: 0 7 * * *
          filters:
            branches:
              only: master
    jobs: *workflow_jobs

jobs:
  node6:
    docker:
      - image: node:6
        user: node
    <<: *unit_tests
  node8:
    docker:
      - image: node:8
        user: node
    <<: *unit_tests
    <<: *test_samples
  node10:
    docker:
      - image: node:10
        user: node
    <<: *unit_tests

  publish_npm:
    docker:
      - image: node:10
        user: node
    steps:
      - checkout
      - run: npm install
      - run: make build
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: npm publish --access=public

  publish_common:
    docker:
      - image: node:10
        user: node
    working_directory: ~/project/src/shared
    steps:
      - checkout ~/project
      - run: npm install
      - run: npm run compile
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: npm publish --access=public
